"""
dump_codebase.py  –  Dumps every source file into a single Markdown file.
On re-runs, only files that changed since the last run are re-included;
unchanged files are skipped so the output never contains duplicate content.
Usage:  python dump_codebase.py
Output: CODEBASE.md  (in the same directory as this script)
"""

import json
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────

ROOT = Path(__file__).parent
OUTPUT = ROOT / "CODEBASE.md"

INCLUDE_EXTENSIONS = {
    ".py", ".js", ".jsx", ".ts", ".tsx",
    ".json", ".yaml", ".yml", ".toml",
    ".html", ".css", ".md", ".txt", ".env",
}

SKIP_DIRS = {
    "node_modules", ".git", "__pycache__", ".venv", "venv",
    "dist", "build", ".next", "coverage", "htmlcov",
    "processed", "versions",          # large data / model artefacts
}

SKIP_FILES = {
    "CODEBASE.md",                     # don't include our own output
    "package-lock.json",
    "dump_codebase.py",                # skip self
    ".dump_cache.json",                # skip cache file
}

MAX_FILE_BYTES = 300_000               # skip files larger than ~300 KB

# ── Helpers ───────────────────────────────────────────────────────────────────

LANG_MAP = {
    ".py": "python", ".js": "javascript", ".jsx": "jsx",
    ".ts": "typescript", ".tsx": "tsx", ".json": "json",
    ".yaml": "yaml", ".yml": "yaml", ".toml": "toml",
    ".html": "html", ".css": "css", ".md": "markdown",
    ".txt": "text", ".env": "bash",
}


def collect_files():
    files = []
    for path in sorted(ROOT.rglob("*")):
        if path.is_dir():
            continue
        # skip unwanted dirs anywhere in the path
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        if path.name in SKIP_FILES:
            continue
        if path.suffix.lower() not in INCLUDE_EXTENSIONS:
            continue
        if path.stat().st_size > MAX_FILE_BYTES:
            continue
        files.append(path)
    return files


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def build_tree(files):
    """Return a simple indented tree string."""
    dirs: dict = {}
    for f in files:
        parts = rel(f).split("/")
        node = dirs
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node[parts[-1]] = None

    lines = []

    def walk(node, prefix=""):
        entries = sorted(node.keys(), key=lambda k: (node[k] is None, k))
        for i, key in enumerate(entries):
            connector = "└── " if i == len(entries) - 1 else "├── "
            lines.append(f"{prefix}{connector}{key}")
            if node[key] is not None:
                extension = "    " if i == len(entries) - 1 else "│   "
                walk(node[key], prefix + extension)

    walk(dirs)
    return "\n".join(lines)


# ── Cache helpers ────────────────────────────────────────────────────────────

CACHE = ROOT / ".dump_cache.json"


def load_cache() -> dict:
    if CACHE.exists():
        try:
            return json.loads(CACHE.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {}


def save_cache(mtimes: dict):
    CACHE.write_text(json.dumps(mtimes, indent=2), encoding="utf-8")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    all_files = collect_files()
    cache = load_cache()
    new_mtimes = {rel(f): f.stat().st_mtime for f in all_files}

    changed = [f for f in all_files if new_mtimes[rel(f)] != cache.get(rel(f))]
    unchanged = len(all_files) - len(changed)

    if not changed:
        print(f"Nothing changed ({len(all_files)} files unchanged). {OUTPUT.name} is up to date.")
        return

    print(f"Found {len(all_files)} files  |  {len(changed)} changed, {unchanged} unchanged – writing {OUTPUT.name} …")

    with OUTPUT.open("w", encoding="utf-8") as out:
        out.write("# AetherSentrix – Full Codebase Dump\n\n")
        out.write("<!-- Auto-generated by dump_codebase.py – only changed files included on re-runs -->\n\n")

        out.write("## Project Structure\n\n```\n")
        out.write(build_tree(changed))
        out.write("\n```\n\n---\n\n")

        current_folder = None
        for path in changed:
            parts = rel(path).split("/")
            folder = parts[0] if len(parts) > 1 else "(root)"

            if folder != current_folder:
                current_folder = folder
                out.write(f"## 📁 {folder}\n\n")

            lang = LANG_MAP.get(path.suffix.lower(), "")
            out.write(f"### `{rel(path)}`\n\n")
            out.write(f"```{lang}\n")
            try:
                out.write(path.read_text(encoding="utf-8", errors="replace"))
            except Exception as exc:
                out.write(f"# [Could not read file: {exc}]\n")
            out.write("\n```\n\n")

    save_cache(new_mtimes)
    size_kb = OUTPUT.stat().st_size / 1024
    print(f"Done!  {OUTPUT.name}  ({size_kb:.1f} KB)")


if __name__ == "__main__":
    main()
